
version: 2
jobs:
  build:
    docker:
      - image: golang:alpine

    steps:
      - checkout

      - run:
          name: Build hsfiles
          command: |
            apk --no-cache add git bash
            mkdir artifacts
            ./build_hsfiles.sh > artifacts/pdepreludat.hsfiles
            cat artifacts/pdepreludat.hsfiles
      - run:
          name: Make release
          command: |
            go get github.com/tcnksm/ghr
            echo Releasing version _${CIRCLE_TAG}_
            ghr -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

