# {{=<% %>=}}
on: [push]
name: build
jobs:
  runhaskell:
    name: Run Haskell
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.4' # Exact version of ghc to use
          cabal-version: '3.10.2.1'
          enable-stack: true
          stack-version: '2.13.1'
      - run: stack test
# <%={{ }}=%>
