on:
  push:
    tags:
      - '*'

jobs:
  updatehsfiles:
    name: Upload Base HS Files
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - run: ./build_hsfiles.sh > pdepreludat.hsfiles
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: upload pdepreludat.hsfiles
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pdepreludat.hsfiles
          asset_name: pdepreludat.hsfiles
          asset_content_type: text/plain